image: Visual Studio 2015

skip_tags: true
branches:
  only:
    - master

platform:
  - x86
  - amd64

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: Hj73NIE1ZHUH7DGShakR4Q==
  GITHUB_USER:
    secure: qozx3wkmakdI3k/sz9Ml8Q==
  GITHUB_EMAIL:
    secure: Xou4FEHMweGQSeay5Q9/LjoLWwlDzMmBa39KYVylgK0=
  GITHUB_TOKEN:
    secure: HImK7idCBTKUB6w7DRTDV/5Ko9+TlZCLOXjbuGNb+InxYQm+H72G8fNPKVcrfcEz

  matrix:
    - VSVER: 9

before_build:
  - ps: >-
      $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))

      If ($env:Platform -Match "x86") {
        $env:VCVARS_PLATFORM="32"
      } Else {
        $env:VCVARS_PLATFORM="64"
      }
  - SET "PLATTYPE=%PLATFORM%"
  - CALL vcvars%VCVARS_PLATFORM%all.bat

build_script:
  - vcbuild

after_build:
  - clean_github "vc%VSVER%.%PLATTYPE%"

artifacts:
    - path: 'src\*.exe'

deploy:
  - provider: GitHub
    artifact: /.*\.exe/
    release: vc$(VSVER).$(PLATTYPE)
    draft: false
    prerelease: false
    force_update: false
    auth_token: $(GITHUB_TOKEN)
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: false      # deploy on tag push only

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

